<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Title>Orchestrator Connector</Title>
    <Description>Program for quickly switching between several Orchestrator Tenants.</Description>
    <Copyright>Copyright (c) 2026 Søren Schytz Birk</Copyright>
    <RepositoryUrl>https://github.com/sorenbcoding/OrchestratorConnector</RepositoryUrl>
    <PackageReleaseNotes>Program for quickly switching between several Orchestrator Tenants.</PackageReleaseNotes>
    <Authors>Søren Schytz Birk</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <ApplicationIcon>Assets\globe-network-color-icon.ico</ApplicationIcon>
    <AssemblyName>Orchestrator Connector</AssemblyName>
    <Version>0.3.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\globe-network-color-icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="9.0.3" />
  </ItemGroup>

</Project>